#include <fstream>
#include <iostream>
#include <string>
#include "../include/game.hpp"

int main(int argc, char **argv)
{
    if (argc < 2)
    {
        std::cerr << "usage: " << argv[0] << " <output path> [simulations per entry]\n";
        return 1;
    }
    const std::size_t simulations = argc > 2 ? std::stoull(argv[2]) : 10'000'000;
    constexpr std::size_t classes = 169;
    constexpr std::size_t playerCounts = preflopTable.size();

    BS::thread_pool<BS::tp::none> pool(std::thread::hardware_concurrency());
    std::vector<std::future<GameStatistics>> results;
    for (std::size_t players = 2; players < playerCounts + 2; ++players)
    {
        for (std::size_t index = 0; index < classes; ++index)
        {
            const std::size_t row = index / 13;
            const std::size_t col = index % 13;
            const std::size_t secondSuit = row > col ? 0 : 1; 
            const Deck hole = Deck::from_mask((1ull << row) | (1ull << (secondSuit * 13 + col)));
            results.push_back(pool.submit_task([=]()
                                               {
                omp::XoroShiro128Plus rng(players * classes + index); 
                return computeRandomGameStatistics(rng, hole, Deck::emptyDeck(), simulations, players); }));
        }
    }

    std::ofstream out(argv[1]);
    out << "// Generated by src/generate_preflop_table.cpp. Do not edit by hand.\n"
        << "// " << simulations << " simulations per entry.\n"
        << "#ifndef __POKER_PREFLOP_TABLE_HPP__\n"
        << "#define __POKER_PREFLOP_TABLE_HPP__\n"
        << "#include <array>\n"
        << "#include <cstdint>\n"
        << "struct PreflopEntry\n{\n    std::uint32_t wins;\n    std::uint32_t ties;\n    std::uint32_t losses;\n    std::uint64_t potShares;\n};\n"
        << "// [numPlayers - 2][preflopClassIndex]; all zero means \"not generated\".\n"
        << "inline constexpr std::array<std::array<PreflopEntry, 169>, " << playerCounts << "> preflopTable{{\n";
    for (std::size_t p = 0; p < playerCounts; ++p)
    {
        out << "    {{\n";
        for (std::size_t index = 0; index < classes; ++index)
        {
            const GameStatistics stats = results[p * classes + index].get();
            out << "        {" << stats.wins << ", " << stats.ties << ", " << stats.losses << ", " << stats.potShares << "},\n";
        }
        out << "    }},\n";
        std::cerr << "players " << p + 2 << " done\n";
    }
    out << "}};\n#endif // __POKER_PREFLOP_TABLE_HPP__\n";
    return 0;
}
